steps:
    # Build the container image
    - id: build image
      name: gcr.io/cloud-builders/docker
      args:
          - build
          - -t
          - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}
          - ${_SERVICE_FOLDER}

    # Push the container image to Artifact Registry
    - id: push image
      name: gcr.io/cloud-builders/docker
      args:
          - push
          - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}

images:
    - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}

substitutions:
    _SERVICE_FOLDER: .
    _REPO_NAME: gpt-bayes # Name of Google Artifact Registry (GAR)'s repo
    _SERVICE_NAME: gpt-bayes # Name of Cloud Run Service
    _REGION: us-central1
