production:
  instanceName: gpt-bayes
  region: us-central1
  zone: us-central1-a
  nginx:
    repoName: gcr2gce-proxy
    serviceName: gcr2gce-proxy
    serverName: nextgen-mmm.pymc-labs.com
    ipAddress: 34.16.56.236
    port: 5000
    region: us-central1
  cloudRun:
    serviceName: gpt-bayes-cloudrun
    modelBucket: gpt-bayes-models
development:
  instanceName: dev-gpt-bayes
  region: us-central1
  zone: us-central1-a
  nginx:
    repoName: dev-gcr2gce-proxy
    serviceName: dev-gcr2gce-proxy
    serverName: dev-nextgen-mmm.pymc-labs.com
    ipAddress: 34.59.137.141
    port: 5000
    region: us-central1
  cloudRun:
    serviceName: dev-gpt-bayes-cloudrun
    modelBucket: dev-bayes-gpt-models
    url: https://dev-gpt-bayes-cloudrun-i66d5bzhua-uc.a.run.app
