name: base
channels:
  - conda-forge
dependencies:
  - python=3.11.0
  - Flask=3.0.3
  - gunicorn=22.0.0
  - pymc-marketing=0.10.0
  - celery=5.4.0 
  - google-cloud-logging=3.11.3
  - redis-server=7.4.0
  - vine=5.1.0
  - redis-py=4.5.0
  - procps-ng
  - yq=2.12.0

